project_name: spacey
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - GITHUB_TOKEN={{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
brews:
  - tap:
      owner: rothgar
      name: homebrew-tap
    homepage: "https://github.com/rothgar/spacey-cli"
    description: "Twitter spaces search CLI"
    license: MIT
    install: |
      bin.install "spacey"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
